### ISSUE TITLE
how to dismiss malert?

### ISSUE THREAD

**Issue by rhfoqkq** [vitormesquita/Malert#10]
how to dismiss malert?

**Comment by vitormesquita** [comment]
Hi @rhfoqkq, thanks for use Malert!

By default we've implemented automatically dismiss when: 

- Touch on buttons with `dismissOnActionTapped: Bool`
- Touch outsisde Malert with `tapToDismiss: Bool`

But if you want dismiss Malert by yourself just call `UIViewController`'s default method 
```swift
dismiss(animated: Bool, completion: (() -> Void))
```
