### ISSUE TITLE
How to know Malert has dismised?

### ISSUE THREAD

**Issue by nazrul-capanicus** [vitormesquita/Malert#12]
How to know Malert has dismised either on tapToDismiss or added button action.
I need to perform some actions when Malert dismiss.

**Comment by vitormesquita** [comment]
Hi @nazrul-capanicus sorry my late,

But I pushed a change on Malert version `3.1.4` that has a method called `onDismiss` to know when Malert has dismissed.

I hope it works for you :D

**Comment by nazrul-capanicus** [comment]
Hi @vitormesquita ,
Thanks for adding requested functionality.
I will update it in my project :)
