### ISSUE TITLE
Can I add picker view on alert ?

### ISSUE THREAD

**Issue by kemalsanli** [vitormesquita/Malert#13]
I couldn't see any example of this, since we can customize views and put in malert, can we do this ?

**Comment by vitormesquita** [comment]
Yes, you can. 

Malert allows you to put any custom view inside it. So I think it's possible to put a UIPickerView with no worries. I've never done it before so if you have any question let me know.

**Comment by kemalsanli** [comment]
<img width="533" alt="Ekran Resmi 2019-11-05 10 26 26" src="https://user-images.githubusercontent.com/22424289/68187116-dab5f780-ffb6-11e9-8acf-d2aa808b398c.png">

Works flawless, much thanks to you.

**Comment by vitormesquita** [comment]
Good!!! Thank you too for being using Malert.
