### ISSUE TITLE
MalertAction how to prevent it auto dismiss ?

### ISSUE THREAD

**Issue by Maxwell6635** [vitormesquita/Malert#14]
MalertAction how to prevent it auto dismiss , we dont want it auto dismiss when click the action. We want to validation first and dismiss manually

**Comment by Maxwell6635** [comment]
OK I found it Malert(title: "", customView: view, tapToDismiss: false, dismissOnActionTapped: false)

**Comment by vitormesquita** [comment]
Cool, if you have other questions let me know!
