### ISSUE TITLE
Incorrect height of custom view

### ISSUE THREAD

**Issue by bwmhamad** [vitormesquita/Malert#15]
Hello,

There's an issue with custom view height when application "Supported interface orientations" is set to portrait but the device is in landscape orientation.

Looks like the issue is following code block of Malert constrains extension (Malert+Constraints.swift):

```swift
if UIDevice.current.orientation.isLandscape {
         let topContraint = malertView.topAnchor.constraint(equalTo: visibleView.topAnchor, constant: 16)
         topContraint.priority = UILayoutPriority(900)
         malertConstraints.append(topContraint)

         let bottomConstraint = malertView.bottomAnchor.constraint(equalTo: visibleView.bottomAnchor, constant: -16)
         bottomConstraint.priority = UILayoutPriority(900)
         malertConstraints.append(bottomConstraint)
}
```

Above if condition doesn't sufficiently checks if landscape orientation is enabled for the application.
I suggest to change above condition statement to:
```swift
if UIDevice.current.orientation.isLandscape && supportedInterfaceOrientations.contains(.landscape) {
    ...
}
```

This way the issue can be avoided by following extension:

```swift
extension Malert {
	public override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
		return .portrait
	}
}
```

Kindly note that this is just something I came up with on the fly to patch this issue so please feel free to implement a better solution if necessary.

Thank you!

**Comment by vitormesquita** [comment]
Hi, thank you to send an issue.

And sure is a problem, Can you send a pull request with these changes? 
Fell free to say no, but will be so nice if you can haha

**Comment by bwmhamad** [comment]
Dear @vitormesquita ,

Thank you for quick reply!
I will try to find a better and more generic solution and create a pull request as soon as possible.

Thank you!
