### ISSUE TITLE
UITableView not displaying when added as customView for Malert

### ISSUE THREAD

**Issue by Ngugi1** [vitormesquita/Malert#7]
I am trying to display a tableview in an Malert prompt and it doesn't work. Is UITableView supported?

**Comment by vitormesquita** [comment]
Hi Ngugi1, Malert can display any `UIView`.

 So Can display `UITableView` because  it is subclass of `UIView`, please see if your constraints are correct :D

I might that the problem is when Malert trying render UITableView. 

I will made this test today and I'll answer you about it. 

Thanks.

**Comment by vitormesquita** [comment]
Hello Ngugi1 Did you fix this issue? 

If Yes Can you share with us how did you do that?

If No Can you explain more What are you doing, please?

Thanks

**Comment by arkilis** [comment]
Same thing happened.

**Comment by vitormesquita** [comment]
Hello guys,

I'll implement a malert with tableView, trying to reproduce this issue. If I will, I'm going fix it or I will put this example on Source.

Thank you are using Malert, I'm very Happy

**Comment by vitormesquita** [comment]
Hello @Ngugi1 and @arkilis, I've made an UITableView example and put in code as [Example9View](https://github.com/vitormesquita/Malert/blob/master/Example/Malert/examples/example9/Example9View.swift), check this example to help you improve your code.

If you need more details please let me know to help you.

For one more time, thank you for are using Malert :D
