### ISSUE TITLE
How to create custom view in alert multiple orientation

### ISSUE THREAD

**Issue by isatria** [vitormesquita/Malert#9]
This is portrait orientation

![simulator screen shot - iphone 5s - 2017-11-21 at 17 11 27](https://user-images.githubusercontent.com/9941418/33066881-12c70a16-cedf-11e7-8479-9d54ed00093c.png)

And this is landscape orientation

![simulator screen shot - iphone 5s - 2017-11-21 at 17 11 31](https://user-images.githubusercontent.com/9941418/33066902-20659f20-cedf-11e7-97e0-e04831a3c99e.png)

Anyone can help to fix this #

**Comment by vitormesquita** [comment]
Hello isatria, thank you to use Malert 

I reproduced this bug too and I'm working to fix it as soon as possible.

**Comment by vitormesquita** [comment]
Hey Isatria, 

I've already fixed this bug in version *2.0*. 

So update your pod to this version and try to use with landscape orientation.

Thanks :)
